planner_concatenator:
  ros__parameters:
    num_input : 3
    input_topic0: "curve_planner/hermite_path"
    input_topic1: "obstacle_planner/hermite_path"
    input_topic2: "stop_planner/hermite_path"