name: Scenario Test

on:
  schedule:
    - cron: 0 0 * * *
  push:
  workflow_dispatch:

jobs:
  scenario_test:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2-beta
    - run: gh run download -n packages
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: OUXT-Polaris/robotx_setup